//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbayCrawlerWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EbayCrawlerWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string amountofpages {
            get {
                return ResourceManager.GetString("amountofpages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,885899667.
        /// </summary>
        internal static string europerdollar {
            get {
                return ResourceManager.GetString("europerdollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,15420678.
        /// </summary>
        internal static string europerpound {
            get {
                return ResourceManager.GetString("europerpound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;s-item  &quot; data-view=&quot;mi:4333|iid:4&quot; id=&quot;srp-river-results-listing1&quot;&gt;&lt;div class=&quot;s-item__wrapper clearfix&quot;&gt;&lt;div class=&quot;s-item__image-section&quot;&gt;&lt;div class=&quot;s-item__image&quot;&gt;&lt;a href=&quot;https://www.ebay.com/itm/WARHAMMER-40K-ELDAR-ARMY-METAL-MANY-UNITS-TO-CHOOSE-FROM/132701935860?var=&amp;amp;hash=item1ee5a6d8f4&quot; tabindex=&quot;-1&quot; aria-hidden=&quot;true&quot; data-track=&quot;{&amp;quot;eventFamily&amp;quot;:&amp;quot;LST&amp;quot;,&amp;quot;eventAction&amp;quot;:&amp;quot;ACTN&amp;quot;,&amp;quot;actionKind&amp;quot;:&amp;quot;NAVSRC&amp;quot;,&amp;quot;actionKinds&amp;quot;:[&amp;quot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nodecontent {
            get {
                return ResourceManager.GetString("nodecontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serializedobj.xml.
        /// </summary>
        internal static string requestsfile {
            get {
                return ResourceManager.GetString("requestsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\rosse\source\repos\EbayCrawler\Content\sites.json.
        /// </summary>
        internal static string urls {
            get {
                return ResourceManager.GetString("urls", resourceCulture);
            }
        }
    }
}
